
aura_denfending_activated = 'images/aura_defending_activated.png'
aura_denfending_neutral = 'images/aura_defending_neutral.png'
auto_attack_allmonster = 'images/auto_attack_allmonster.png'

boss_angeling = 'images/boss_angeling.png'
boss_button_go = 'images/boss_button_go.png'
boss_coming_angeling = 'images/boss_coming_angeling.png'
boss_coming_deviling = 'images/boss_coming_deviling.png'
boss_coming_doppel = 'images/boss_coming_doppel.png'
boss_coming_drake = 'images/boss_coming_drake.png'
boss_coming_dracula = 'images/boss_coming_dracula.png'
boss_coming_goblin_chief = 'images/boss_coming_goblin_chief.png'
boss_coming_golden_thief_bug = 'images/boss_coming_golden_thief_bug.png'
boss_coming_eddga = 'images/boss_coming_eddga.png'
boss_coming_maya = 'images/boss_coming_maya.png'
boss_coming_mistress = 'images/boss_coming_mistress.png'
boss_coming_moonlight = 'images/boss_coming_moonlight.png'
boss_coming_orc_hero = 'images/boss_coming_orc_hero.png'
boss_coming_orc_lord = 'images/boss_coming_orc_lord.png'
boss_coming_osiris = 'images/boss_coming_osiris.png'
boss_coming_pharaoh = 'images/boss_coming_pharaoh.png'
boss_coming_phreeoni = 'images/boss_coming_phreeoni.png'
boss_deviling = 'images/boss_deviling.png'
boss_doppelganger = 'images/boss_doppelganger.png'
boss_drag_icon = 'images/boss_drag_icon.png'
boss_dracula = 'images/boss_dracula.png'
boss_drake = 'images/boss_drake.png'
boss_eddga = 'images/boss_eddga.png'
boss_goblin_chief = 'images/boss_goblin_chief.png'
boss_golden_thief_bug = 'images/boss_golden_thief_bug.png'
boss_maya = 'images/boss_maya.png'
boss_moonlight = 'images/boss_moonlight.png'
boss_map_ant_hell = 'images/boss_map_ant_hell.png'
boss_map_deep_payon_forest = 'images/boss_map_deep_payon_forest.png'
boss_map_garden = 'images/boss_map_garden.png'
boss_map_geffen_underground_2f = 'images/boss_map_geffen_underground_2f.png'
boss_map_geffen_underground_3f = 'images/boss_map_geffen_underground_3f.png'
boss_map_goblin_forest = 'images/boss_map_goblin_forest.png'
boss_map_poring_island = 'images/boss_map_poring_island.png'
boss_map_culvert_2f = 'images/boss_map_culvert_2f.png'
boss_map_orc_village = 'images/boss_map_orc_village.png'
boss_map_southern_sograt = 'images/boss_map_southern_sograt.png'
boss_map_sphinx_crypt_level_2 = 'images/boss_map_sphinx_crypt_level_2.png'
boss_map_payon_cave_3f = 'images/boss_map_payon_cave_3f.png'
boss_map_pyramid_3f = 'images/boss_map_pyramid_3f.png'
boss_map_shipwreck_labyrinth = 'images/boss_map_shipwreck_labyrinth.png'
boss_mistress = 'images/boss_mistress.png'
boss_orc_hero = 'images/boss_orc_hero.png'
boss_orc_lord = 'images/boss_orc_lord.png'
boss_osiris = 'images/boss_osiris.png'
boss_pharaoh = 'images/boss_pharaoh.png'
boss_phreeoni = 'images/boss_phreeoni.png'
boss_region_angeling = 'images/boss_region_angeling.png'
boss_region_deviling = 'images/boss_region_deviling.png'
boss_region_doppelganger = 'images/boss_region_doppelganger.png'
boss_region_dracula = 'images/boss_region_dracula.png'
boss_region_drake = 'images/boss_region_drake.png'
boss_region_eddga = 'images/boss_region_eddga.png'
boss_region_goblin_chief = 'images/boss_region_goblin_chief.png'
boss_region_golden_thief_bug = 'images/boss_region_golden_thief_bug.png'
boss_region_maya = 'images/boss_region_maya.png'
boss_region_mistress = 'images/boss_region_mistress.png'
boss_region_moonlight = 'images/boss_region_moonlight.png'
boss_region_orc_hero = 'images/boss_region_orc_hero.png'
boss_region_orc_lord = 'images/boss_region_orc_lord.png'
boss_region_osiris = 'images/boss_region_osiris.png'
boss_region_pharaoh = 'images/boss_region_pharaoh.png'
boss_region_phreeoni = 'images/boss_region_phreeoni.png'
boss_title_mvp = 'images/boss_title_mvp.png'

button_auto_attack_close = 'images/button_auto_attack_close.png'
button_battle_log = 'images/button_battle_log.png'
button_go = 'images/button_go.png'
button_agree = 'images/button_agree.png'
button_send = 'images/button_send.png'
button_escape = 'images/button_escape.png'
button_confirm = 'images/button_confirm.png'
button_map_close = 'images/button_map_close.png'
button_quick_departure = 'images/button_quick_departure.png'

chat_tab_party_inactive = 'images/chat_tab_party_inactive.png'
chat_tab_party_active = 'images/chat_tab_party_active.png'
chat_tab_world_inactive = 'images/chat_tab_world_inactive.png'
chat_tab_world_active = 'images/chat_tab_world_active.png'

die_instance_respawn = 'images/die_instant_respawn.png'
die_upgrade_title = 'images/die_upgrade_title.png'

event_boss = 'images/event_boss.png'
event_boss_inactive = 'images/event_boss_inactive.png'
event_daily_inactive = 'images/event_daily_inactive.png'
event_drag_icon = 'images/event_drag_icon.png'
event_side_menu = 'images/event_side_menu.png'
event_menu1 = 'images/event_menu1.png'
event_menu2 = 'images/event_menu2.png'

icon_auto_attack = 'images/icon_auto_attack.png'
icon_auto_attack_boss = 'images/icon_auto_attack_boss.png'
icon_boss = 'images/icon_boss.png'
icon_boss_left = 'images/icon_boss_left.png'
icon_boss_right = 'images/icon_boss_right.png'
icon_boss_top = 'images/icon_boss_top.png'
icon_boss_bottom = 'images/icon_boss_bottom.png'

menu_daily = 'images/menu_daily.png'

party_number_2 = 'images/party_number_2.png'
party_number_3 = 'images/party_number_3.png'
party_number_3 = 'images/party_number_3.png'
party_number_4 = 'images/party_number_4.png'
party_number_5 = 'images/party_number_5.png'

pet_earthlord = 'images/pet_icon_earthlord.png'
pet_dunell = 'images/pet_icon_dunell.png'
pet_barfo = 'images/pet_icon_barfo.png'

profile = 'images/profile.png'

oracle_present = 'images/oracle_present.png'

tap_anywhere = 'images/tap_anywhere.png'
team_confirm = 'images/team_confirm.png'

wing = 'images/wing.png'
victory = 'images/anthem_victory.png'


